name: Common Execution Access

on:
  workflow_dispatch:
    inputs:
      test_path:
        description: 'Path to tests'
        required: false
        default: 'otaiE2ETest/tests/'
      env:
        description: 'Environment to run tests in (dev, test, staging)'
        required: false
        default: 'test'

jobs:
  setup-env:
    runs-on: ubuntu-latest
    outputs:
      RF_ENV: ${{ steps.setenv.outputs.RF_ENV }}
    steps:
      - name: Set environment name
        id: setenv
        run: |
          ENV_INPUT="${{ github.event.inputs.env }}"
          if [ -z "$ENV_INPUT" ]; then
            ENV_INPUT="test"
          fi
          echo "RF_ENV=$ENV_INPUT" >> $GITHUB_OUTPUT

  test-data:
    needs: setup-env
    runs-on: ubuntu-latest
    env:
      RF_ENV: ${{ needs.setup-env.outputs.RF_ENV }}
      HEADLESS: "true"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run Test++:001
        run: |
          source venv/bin/activate
          set -a
          source otaiE2ETest/env_files/${{ env.RF_ENV }}.env
          set +a
          robot --outputdir results/001 --include "Test++:001" otaiE2ETest/tests/

      - name: Run Test++:002
        run: |
          source venv/bin/activate
          robot --outputdir results/002 --include "Test++:002" otaiE2ETest/tests/

      - name: Run Test++:003
        run: |
          source venv/bin/activate
          robot --outputdir results/003 --include "Test++:003" otaiE2ETest/tests/

      - name: Upload Test Data Reports
        uses: actions/upload-artifact@v4
        with:
          name: pretest-results
          path: |
            results/001/
            results/002/
            results/003/

  run-remain-tests:
    needs: [setup-env, test-data]
    runs-on: ubuntu-latest
    env:
      RF_ENV: ${{ needs.setup-env.outputs.RF_ENV }}
      HEADLESS: "true"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run Remaining Tests
        run: |
          source venv/bin/activate
          set -a
          source otaiE2ETest/env_files/${{ env.RF_ENV }}.env
          set +a
          robot --outputdir results/remain --exclude "Test++:001|Test++:002|Test++:003" otaiE2ETest/tests/

      - name: Upload Remaining Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: remain-results
          path: results/remain/

  generate-report:
    needs: [test-data, run-remain-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Download All Reports
        uses: actions/download-artifact@v4
        with:
          path: all-results/

      - name: Combine and Generate Final Report
        run: |
          mkdir -p final-results
          cp -r all-results/* final-results/
          echo "All test results combined in final-results directory."

      - name: Upload Final Combined Report
        uses: actions/upload-artifact@v4
        with:
          name: all-combined-reports
          path: final-results/
