name: E2E Tests with Required State Setup

on:
  workflow_dispatch:
    inputs:
      test_path:
        description: 'Path to tests'
        required: false
        default: 'otaiE2ETest/tests/'
      env:
        description: 'Environment to run tests in (dev, test, staging)'
        required: false
        default: 'test'

jobs:
  setup-env:
    runs-on: ubuntu-latest
    outputs:
      RF_ENV: ${{ steps.setenv.outputs.RF_ENV }}
    steps:
      - name: Set environment name
        id: setenv
        run: |
          ENV_INPUT="${{ github.event.inputs.env }}"
          if [ -z "$ENV_INPUT" ]; then
            ENV_INPUT="test"
          fi
          echo "RF_ENV=$ENV_INPUT" >> $GITHUB_OUTPUT

  pre-test-setup:
    needs: setup-env
    runs-on: ubuntu-latest
    env:
      RF_ENV: ${{ needs.setup-env.outputs.RF_ENV }}
      HEADLESS: "true"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt robotframework

      - name: Run Test++:001
        run: |
          source venv/bin/activate
          set -a
          source otaiE2ETest/env_files/${{ env.RF_ENV }}.env
          set +a
          robot --outputdir results/001 --include "Test++:001" otaiE2ETest/tests/

      - name: Run Test++:002
        run: |
          source venv/bin/activate
          robot --outputdir results/002 --include "Test++:002" otaiE2ETest/tests/

      - name: Run Test++:003
        run: |
          source venv/bin/activate
          robot --outputdir results/003 --include "Test++:003" otaiE2ETest/tests/

      - name: Merge Pre-test Reports
        run: |
          source venv/bin/activate
          rebot --output results/pretest-output.xml \
                --report results/pretest-report.html \
                --log results/pretest-log.html \
                results/001/output.xml results/002/output.xml results/003/output.xml

      - name: Upload Pre-test Combined Report
        uses: actions/upload-artifact@v4
        with:
          name: pretest-results
          path: |
            results/pretest-output.xml
            results/pretest-log.html
            results/pretest-report.html

  run-remain-tests:
    needs: [setup-env, pre-test-setup]
    runs-on: ubuntu-latest
    env:
      RF_ENV: ${{ needs.setup-env.outputs.RF_ENV }}
      HEADLESS: "true"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt robotframework

      - name: Run Remaining Tests
        run: |
          source venv/bin/activate
          set -a
          source otaiE2ETest/env_files/${{ env.RF_ENV }}.env
          set +a
          robot --outputdir results/remain \
            --exclude "Test++:001" \
            --exclude "Test++:002" \
            --exclude "Test++:003" \
            otaiE2ETest/tests/

      - name: Upload Remaining Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: remain-results
          path: results/remain/

  generate-report:
    needs: [pre-test-setup, run-remain-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Download Pre-test Report
        uses: actions/download-artifact@v4
        with:
          name: pretest-results
          path: results/

      - name: Download Remaining Test Report
        uses: actions/download-artifact@v4
        with:
          name: remain-results
          path: results/remain/

      - name: Combine Final Report
        run: |
          pip install robotframework
          rebot --output results/all-output.xml \
                --report results/all-report.html \
                --log results/all-log.html \
                results/pretest-output.xml results/remain/output.xml

      - name: Upload Final Combined Report
        uses: actions/upload-artifact@v4
        with:
          name: all-combined-reports
          path: |
            results/all-output.xml
            results/all-report.html
            results/all-log.html