name: Run Robot Framework Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
    inputs:
      test_path:
        description: 'Path to tests'
        required: false
        default: 'otaiE2ETest/tests/'
      test_tags:
        description: 'Tags to include (optional)'
        required: false
        default: 'LotfiOTAI AND Test++'
      exclude_tags:
        description: 'Tags to exclude (optional)'
        required: false
        default: ''
      env:
        description: 'Environment to run tests in (dev, test, prod)'
        required: false
        default: 'test'

jobs:
  run-e2e-tests:
    name: Run RobotFramework E2E Tests
    runs-on: ubuntu-latest
    outputs:
      test_output: ${{ steps.set-output.outputs.test_output }}

    env:
      RF_ENV: ${{ github.event.inputs.env }}
      HEADLESS: "true"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run Robot Framework tests
        id: set-output
        run: |
          source venv/bin/activate
          TEST_PATH="${{ github.event.inputs.test_path }}"
          INCLUDE_TAGS="${{ github.event.inputs.test_tags }}"
          EXCLUDE_TAGS="${{ github.event.inputs.exclude_tags }}"

          CMD="robot --outputdir results"
          if [ ! -z "$INCLUDE_TAGS" ]; then
            CMD="$CMD --include \"$INCLUDE_TAGS\""
          fi
          if [ ! -z "$EXCLUDE_TAGS" ]; then
            CMD="$CMD --exclude \"$EXCLUDE_TAGS\""
          fi
          CMD="$CMD \"$TEST_PATH\""

          echo "Running command: $CMD"
          eval $CMD

  generate-report:
    name: Generate E2E Report
    runs-on: ubuntu-latest
    needs: run-e2e-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Robot Framework results
        uses: actions/download-artifact@v4
        with:
          name: robot-results
          path: results/

      - name: Display log.html as summary (optional)
        run: |
          echo "Tests completed. You can find detailed logs in results/log.html"

      - name: Upload Robot Framework reports
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: results/
